from __future__ import annotations

from pathlib import Path

from .models import FileRecord, ScanReport
from .scanner import SECRET_LIKE_NAMES, scan_repository


DEFAULT_MAX_FILE_CHARS = 12_000


def build_repository_pack(
    root: str | Path,
    *,
    max_file_chars: int = DEFAULT_MAX_FILE_CHARS,
    include_contents: bool = True,
) -> str:
    report = scan_repository(root)
    root_path = Path(report.root)

    sections = [
        "# ProjectLens Repository Pack",
        "",
        "This file is generated by ProjectLens AI. It is designed to give an AI",
        "assistant structured context about a code repository.",
        "",
        "## Repository Summary",
        "",
        f"- Root: `{report.root}`",
        f"- Files indexed: {report.file_count}",
        f"- Total size: {_format_bytes(report.total_size_bytes)}",
        f"- Code symbols found: {report.symbol_count}",
        f"- Technologies: {', '.join(report.technologies) if report.technologies else 'unknown'}",
        f"- Entrypoints: {', '.join(report.entrypoints) if report.entrypoints else 'not detected'}",
        "",
        "## Language Capabilities",
        "",
        *_build_capability_lines(report),
        "",
        "## Directory Tree",
        "",
        "```text",
        *_build_tree_lines(report.files),
        "```",
        "",
        "## Important Files",
        "",
        *_build_file_table(report.files),
        "",
        "## Code Symbols",
        "",
        *_build_symbol_lines(report),
        "",
    ]

    if report.warnings:
        sections.extend(["## Warnings", ""])
        sections.extend(f"- {warning}" for warning in report.warnings)
        sections.append("")

    if include_contents:
        sections.extend(["## File Contents", ""])
        for file in _content_files(report.files):
            sections.extend(_build_file_content(root_path, file, max_file_chars=max_file_chars))

    return "\n".join(sections).rstrip() + "\n"


def write_repository_pack(
    root: str | Path,
    output: str | Path,
    *,
    max_file_chars: int = DEFAULT_MAX_FILE_CHARS,
    include_contents: bool = True,
) -> Path:
    text = build_repository_pack(root, max_file_chars=max_file_chars, include_contents=include_contents)
    output_path = Path(output).expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(text, encoding="utf-8")
    return output_path


def _build_capability_lines(report: ScanReport) -> list[str]:
    if not report.language_capabilities:
        return ["No source language files detected."]

    lines = [
        "| Language | Support | Confidence | Files | Symbols | Imports | Parser |",
        "| --- | --- | --- | ---: | ---: | ---: | --- |",
    ]
    for capability in report.language_capabilities:
        lines.append(
            f"| {capability.language} | {capability.support_level} | {capability.confidence} | "
            f"{capability.file_count} | {capability.symbol_count} | {capability.import_count} | "
            f"{capability.parser} |"
        )
    lines.extend(
        [
            "",
            "Support meanings: `deep` means compiler/AST-level symbol extraction; `structured` means",
            "tested navigation-grade extraction for common code patterns; `fallback` means file/path/keyword/embedding search only.",
        ]
    )
    return lines


def _build_tree_lines(files: list[FileRecord]) -> list[str]:
    if not files:
        return ["(empty)"]
    return [file.path for file in sorted(files, key=lambda item: item.path)]


def _build_file_table(files: list[FileRecord]) -> list[str]:
    if not files:
        return ["No files detected."]

    lines = ["| Path | Role | Size |", "| --- | --- | --- |"]
    priority = {"documentation": 0, "dependency-or-config": 1, "source": 2, "test": 3, "ci": 4}
    sorted_files = sorted(files, key=lambda item: (priority.get(item.role, 9), item.path))
    for file in sorted_files[:40]:
        lines.append(f"| `{file.path}` | {file.role} | {_format_bytes(file.size_bytes)} |")
    if len(sorted_files) > 40:
        lines.append(f"| ... | {len(sorted_files) - 40} more files omitted from this table | |")
    return lines


def _build_symbol_lines(report: ScanReport) -> list[str]:
    if not report.symbols:
        return ["No code symbols detected."]

    lines = ["| Symbol | Kind | Location |", "| --- | --- | --- |"]
    for symbol in report.symbols[:100]:
        location = f"{symbol.path}:{symbol.line}"
        lines.append(f"| `{symbol.name}` | {symbol.kind} | `{location}` |")
    if len(report.symbols) > 100:
        lines.append(f"| ... | {len(report.symbols) - 100} more symbols omitted | |")
    return lines


def _content_files(files: list[FileRecord]) -> list[FileRecord]:
    allowed_roles = {"documentation", "dependency-or-config", "source", "test", "ci"}
    return [
        file
        for file in sorted(files, key=lambda item: item.path)
        if file.role in allowed_roles and file.path.rsplit("/", maxsplit=1)[-1] not in SECRET_LIKE_NAMES
    ]


def _build_file_content(root: Path, file: FileRecord, *, max_file_chars: int) -> list[str]:
    path = root / file.path
    language = _markdown_language(file.suffix)
    try:
        text = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return [
            f"### `{file.path}`",
            "",
            "_Skipped: file could not be read as UTF-8 text._",
            "",
        ]

    truncated = len(text) > max_file_chars
    if truncated:
        text = text[:max_file_chars].rstrip() + "\n\n[ProjectLens: file truncated]"

    return [
        f"### `{file.path}`",
        "",
        f"```{language}",
        text.rstrip(),
        "```",
        "",
    ]


def _markdown_language(suffix: str) -> str:
    return {
        ".py": "python",
        ".toml": "toml",
        ".json": "json",
        ".md": "markdown",
        ".yml": "yaml",
        ".yaml": "yaml",
        ".js": "javascript",
        ".jsx": "jsx",
        ".ts": "typescript",
        ".tsx": "tsx",
        ".go": "go",
        ".rs": "rust",
        ".java": "java",
        ".cs": "csharp",
        ".php": "php",
        ".rb": "ruby",
    }.get(suffix.lower(), "")


def _format_bytes(value: int) -> str:
    if value < 1024:
        return f"{value} B"
    if value < 1024 * 1024:
        return f"{value / 1024:.1f} KB"
    return f"{value / (1024 * 1024):.1f} MB"